export interface TravelMarker {
  label: string;
  coordinates: [number, number];
}

export interface TravelPlace {
  id: string;
  label: string;
  country: string;
  countryId: string;
  period: string;
  markers: TravelMarker[];
  photos: string[];
  cover?: string;
}

const photoPaths = (folder: string, count: number, extension = "jpg") =>
  Array.from({ length: count }, (_, index) =>
    `/images/travel/${folder}/${index + 1}.${extension}`,
  );

export const travelPlaces: TravelPlace[] = [
  {
    id: "hong-kong",
    label: "Hong Kong",
    country: "China",
    countryId: "156",
    period: "2023.05",
    markers: [{ label: "Hong Kong", coordinates: [114.17, 22.32] }],
    photos: photoPaths("hong-kong", 9, "png"),
  },
  {
    id: "ulanqab",
    label: "Ulanqab",
    country: "China",
    countryId: "156",
    period: "2023.06",
    markers: [{ label: "Ulanqab", coordinates: [113.11, 41.03] }],
    photos: photoPaths("ulanqab", 9, "png"),
  },
  {
    id: "austria",
    label: "Austria",
    country: "Austria",
    countryId: "040",
    period: "2023.08",
    markers: [{ label: "Austria", coordinates: [14.55, 47.52] }],
    photos: photoPaths("austria", 9, "png"),
  },
  {
    id: "hungary",
    label: "Hungary",
    country: "Hungary",
    countryId: "348",
    period: "2023.08",
    markers: [{ label: "Hungary", coordinates: [19.5, 47.16] }],
    photos: photoPaths("hungary", 9, "png"),
  },
  {
    id: "brno",
    label: "Brno",
    country: "Czechia",
    countryId: "203",
    period: "2023.08",
    markers: [{ label: "Brno", coordinates: [16.61, 49.2] }],
    photos: photoPaths("brno", 8, "png"),
  },
  {
    id: "prague",
    label: "Prague",
    country: "Czechia",
    countryId: "203",
    period: "2023.08",
    markers: [{ label: "Prague", coordinates: [14.42, 50.08] }],
    photos: photoPaths("prague", 9, "png"),
  },
  {
    id: "balaton",
    label: "Balaton",
    country: "Hungary",
    countryId: "348",
    period: "2023.08",
    markers: [{ label: "Balaton", coordinates: [17.73, 46.88] }],
    photos: photoPaths("balaton", 9, "png"),
  },
  {
    id: "budapest",
    label: "Budapest",
    country: "Hungary",
    countryId: "348",
    period: "2023.08",
    markers: [{ label: "Budapest", coordinates: [19.04, 47.5] }],
    photos: photoPaths("budapest", 9, "png"),
  },
  {
    id: "sopron-gyor",
    label: "Sopron · Gyor",
    country: "Hungary",
    countryId: "348",
    period: "2023.08",
    markers: [
      { label: "Sopron", coordinates: [16.59, 47.69] },
      { label: "Gyor", coordinates: [17.63, 47.69] },
    ],
    photos: photoPaths("sopron-gyor", 6, "png"),
  },
  {
    id: "dubai",
    label: "Dubai",
    country: "United Arab Emirates",
    countryId: "784",
    period: "2023.08",
    markers: [{ label: "Dubai", coordinates: [55.27, 25.2] }],
    photos: photoPaths("dubai", 9, "png"),
    cover: "/images/travel/dubai/4.png",
  },
  {
    id: "jilin",
    label: "Jilin",
    country: "China",
    countryId: "156",
    period: "2023.10",
    markers: [{ label: "Jilin", coordinates: [126.55, 43.84] }],
    photos: photoPaths("jilin", 11, "png"),
  },
  {
    id: "malaysia",
    label: "Malaysia",
    country: "Malaysia",
    countryId: "458",
    period: "2023.11",
    markers: [{ label: "Malaysia", coordinates: [102.0, 4.21] }],
    photos: photoPaths("malaysia", 9, "png"),
  },
  {
    id: "australia-2024",
    label: "Australia",
    country: "Australia",
    countryId: "036",
    period: "2024.02",
    markers: [{ label: "Australia", coordinates: [133.78, -25.27] }],
    photos: photoPaths("australia-2024", 9),
  },
  {
    id: "uzbekistan",
    label: "Uzbekistan",
    country: "Uzbekistan",
    countryId: "860",
    period: "2024.04",
    markers: [{ label: "Uzbekistan", coordinates: [64.59, 41.38] }],
    photos: photoPaths("uzbekistan", 9),
  },
  {
    id: "vietnam",
    label: "Vietnam",
    country: "Vietnam",
    countryId: "704",
    period: "2024.06",
    markers: [{ label: "Vietnam", coordinates: [106.3, 16.32] }],
    photos: photoPaths("vietnam", 6),
  },
  {
    id: "mozambique",
    label: "Mozambique",
    country: "Mozambique",
    countryId: "508",
    period: "2024.07",
    markers: [{ label: "Mozambique", coordinates: [35.53, -18.67] }],
    photos: photoPaths("mozambique", 9),
  },
  {
    id: "botswana",
    label: "Botswana",
    country: "Botswana",
    countryId: "072",
    period: "2024.08",
    markers: [{ label: "Botswana", coordinates: [24.68, -22.33] }],
    photos: photoPaths("botswana", 8),
  },
  {
    id: "zambia",
    label: "Zambia",
    country: "Zambia",
    countryId: "894",
    period: "2024.08",
    markers: [{ label: "Zambia", coordinates: [27.85, -13.13] }],
    photos: photoPaths("zambia", 4),
  },
  {
    id: "japan-2024",
    label: "Japan",
    country: "Japan",
    countryId: "392",
    period: "2024.12",
    markers: [{ label: "Japan", coordinates: [138.25, 36.2] }],
    photos: photoPaths("japan-2024", 6),
  },
  {
    id: "germany",
    label: "Germany",
    country: "Germany",
    countryId: "276",
    period: "2025.02",
    markers: [{ label: "Germany", coordinates: [10.45, 51.17] }],
    photos: photoPaths("germany", 5),
  },
  {
    id: "netherlands",
    label: "Netherlands",
    country: "Netherlands",
    countryId: "528",
    period: "2025.02",
    markers: [{ label: "Netherlands", coordinates: [5.29, 52.13] }],
    photos: photoPaths("netherlands", 5),
  },
  {
    id: "guizhou",
    label: "Guizhou",
    country: "China",
    countryId: "156",
    period: "2025.04",
    markers: [{ label: "Guizhou", coordinates: [106.71, 26.58] }],
    photos: photoPaths("guizhou", 4),
  },
  {
    id: "indonesia",
    label: "Indonesia",
    country: "Indonesia",
    countryId: "360",
    period: "2025.05",
    markers: [{ label: "Indonesia", coordinates: [113.92, -0.79] }],
    photos: photoPaths("indonesia", 10),
  },
  {
    id: "foshan",
    label: "Foshan",
    country: "China",
    countryId: "156",
    period: "2025.07",
    markers: [{ label: "Foshan", coordinates: [113.12, 23.02] }],
    photos: [],
  },
  {
    id: "japan-2025",
    label: "Japan",
    country: "Japan",
    countryId: "392",
    period: "2025.08",
    markers: [{ label: "Japan", coordinates: [138.25, 36.2] }],
    photos: [],
  },
  {
    id: "queensland",
    label: "Queensland",
    country: "Australia",
    countryId: "036",
    period: "2025.08",
    markers: [{ label: "Queensland", coordinates: [145, -20.92] }],
    photos: [],
  },
  {
    id: "kashgar",
    label: "Kashgar",
    country: "China",
    countryId: "156",
    period: "2025.09",
    markers: [{ label: "Kashgar", coordinates: [75.99, 39.47] }],
    photos: photoPaths("kashgar", 6),
  },
  {
    id: "shangrao",
    label: "Shangrao",
    country: "China",
    countryId: "156",
    period: "2025.10",
    markers: [{ label: "Shangrao", coordinates: [117.97, 28.45] }],
    photos: photoPaths("shangrao", 6),
  },
  {
    id: "texas",
    label: "Texas",
    country: "United States",
    countryId: "840",
    period: "2026.03",
    markers: [{ label: "Texas", coordinates: [-99.9, 31.97] }],
    photos: photoPaths("texas", 6),
  },
  {
    id: "bay-area",
    label: "San Francisco Bay Area",
    country: "United States",
    countryId: "840",
    period: "2026.03",
    markers: [{ label: "San Francisco Bay Area", coordinates: [-122.27, 37.8] }],
    photos: photoPaths("bay-area", 9),
  },
  {
    id: "baja-california",
    label: "Baja California",
    country: "Mexico",
    countryId: "484",
    period: "2026.04",
    markers: [{ label: "Baja California", coordinates: [-115.28, 30.84] }],
    photos: photoPaths("baja-california", 9),
  },
  {
    id: "los-angeles-san-diego",
    label: "Los Angeles · San Diego",
    country: "United States",
    countryId: "840",
    period: "2026.04",
    markers: [
      { label: "Los Angeles", coordinates: [-118.24, 34.05] },
      { label: "San Diego", coordinates: [-117.16, 32.72] },
    ],
    photos: photoPaths("los-angeles-san-diego", 9),
  },
  {
    id: "seattle",
    label: "Seattle",
    country: "United States",
    countryId: "840",
    period: "2026.07",
    markers: [{ label: "Seattle", coordinates: [-122.33, 47.61] }],
    photos: photoPaths("seattle", 9, "png"),
  },
  {
    id: "salt-lake-city-yellowstone",
    label: "Salt Lake City · Yellowstone",
    country: "United States",
    countryId: "840",
    period: "2026.07",
    markers: [
      { label: "Salt Lake City", coordinates: [-111.89, 40.76] },
      { label: "Yellowstone", coordinates: [-110.59, 44.43] },
    ],
    photos: photoPaths("salt-lake-city-yellowstone", 9, "png"),
  },
];

export const travelPhotoCount = travelPlaces.reduce(
  (total, place) => total + place.photos.length,
  0,
);

export const visitedCountryIds = new Set(
  travelPlaces.map(place => place.countryId),
);